version: "3.7"

services:
  api_service:
    build: .
    ports:
      - 8080:8080
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/smartwateringv2
      - spring.datasource.username=root
      - spring.datasource.password=
    depends_on:
      - mysqldb
    networks:
      - mynetwork
    restart: always

  mysqldb:
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=smartwateringv2
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
